@startuml
scale 1.3
skinparam shadowing false
skinparam sequenceMessageAlign center
skinparam maxMessageSize 80
title Customer Activation (Übersicht)

actor "Employee" as E
participant "API" as API
box "BC Customer" #EEF
participant "CustomerUcActivate" as U
end box
box "BC Employee" #EFE
participant "EmployeesContract" as EC
end box
box "BC Core" #FFE
participant "AccountsContract" as AC
end box

E -> API : ActivateCustomer(customerId, iban?)
API -> U : Execute(customerId, iban?)

U -> EC : RequireEmployee(CustomerActivate)
EC --> U : EmployeeId / Forbidden

U -> AC : OpenInitialAccount(customerId, iban?)
AC --> U : OK / Error

U --> API : Success / Failure
API --> E : 200 / 4xx
@enduml
