import EmployeePost.http
import CustomerPost.http
import AccountPost.http
import BeneficiaryPost.http
import TransferSendMoney.http

###
run EmployeePost.http

###
run CustomerPost.http

###
run AccountPost.http

###
run BeneficiaryPost.http

###
### run TransferSendMoney.http