import EmployeePost.http
import CustomerPost.http
import AccountPost.http
import BeneficiaryPost.http
import TransferSendMoney.http

###
run EmployeePost_Create.http

###
run CustomerPost_Create.http

###
run AccountPost_Create.http

###
run BeneficiaryPost_Create.http

###
### run TransferSendMoney.http