@baseUrl = https://localhost:8010/banking/v2

###
PUT {{baseUrl}}/customers/10000000-0000-0000-0000-000000000000
Content-Type: application/json
Accept: application/json

{
  "email": "erika.mustermann@freenet.de",
  "addressDto": {
    "street": "Hannoverschen Str. 123",
    "postalCode": "30826",
    "city": "Garbsen",
    "country": "DE"
  }
}
